# -*- coding: utf-8 -*-
"""CORRELACIÓN.ipynb

Automatically generated by Colab.

Se desarrolla un ejercicio que evalúa la correlación entre el stock del producto y las ventas históricas registradas.

Original file is located at
    https://colab.research.google.com/drive/1g0n6UwVlXHnOTPCqObCAWadnVj6aBsNP
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr
spark = SparkSession.builder.appName('CORRELACION').getOrCreate()

data = spark.read.csv("Productos2.csv", header=True, inferSchema=True, sep=";")

data.show()

correlacion = data.select(corr(col("Stock"), col("Ventas")).alias("Correlación")).collect()[0]["Correlación"]

print(f"La correlación entre Stock y Ventas es {correlacion}.")

# Vamos a modificar los datos para tener un mínimo de 0.5
data2 = spark.read.csv("Productos3.csv", header=True, inferSchema=True, sep=";")
data2.show()

correlacion = data2.select(corr(col("Stock"), col("Ventas")).alias("Correlación")).collect()[0]["Correlación"]

print(f"La nueva correlación entre Stock y Ventas es {correlacion}.")
