# -*- coding: utf-8 -*-
"""MEDIA.ipynb

Se desarrolla un ejercicio que muestra en una tabla el promedio del stock de productos de Tai Loy registrados 

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11gT-_THIH3AF3S1iIVdcLVfKBSJ4-fqh
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr
spark = SparkSession.builder.appName('MEDIA').getOrCreate()

# Cargar el dataset
data = spark.read.csv("Productos.csv", header=True, inferSchema=True, sep=";")

data.show()

# Calcular la media de los stock registrados en los productos
stock_mean = data.select(mean(col("Stock")).alias("Mean"))

print(f"La media de los stock de productos registrados es")
stock_mean.show()
